image: python:3.8

stages:
  - test

test_job:
  stage: test
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  cache:
    paths:
      - .cache/pip
      - venv/

  before_script:
    - python --version  # For debugging
    - apt-get update -y  # Обновляем список пакетов (для Debian/Ubuntu)
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt

  script:
    - echo "Hello, world!"p
    - pytest
    - flake8 .
