image: python:3.8

stages:
  - test

test_job:
  stage: test
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  cache:
    paths:
      - .cache/pip
      - venv/

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - export PYTHONPATH=$PYTHONPATH:/builds/lollolol/fastapi-calculator
  - pip install -r requirements.txt

  script:
    - echo "Hello, world!"
    - pytest
    - flake8
    - mypy