[tool.mypy]
python_version = "3.8"
warn_unused_configs = true


[[tool.mypy.overrides]]
module = "src.*"
ignore_missing_imports = true


[tool.flake8]
max-line-length = 120
extend-ignore = "E203, W503"


[tool.pytest.ini_options]
    testpaths = ["tests"]